### PR TITLE
rearranged

### PR DESCRIPTION
**Pull request by John-Colvin**

### CODE REVIEW

**Comment by 9il** [comment]
You can remove `configurations` thought

**Comment by John-Colvin** [comment]
not until we've swapped over to the new docs building setup. It's a workaround for a dub bug to do with sourceLibraries and docs

**Comment by 9il** [comment]
What the bug?

**Comment by John-Colvin** [comment]
https://github.com/D-Programming-Language/dub/issues/553 the fix should be in 0.9.24 release

**Comment by 9il** [comment]
Why not to skip `targetType` at all? This is optional field.

**Comment by 9il** [comment]
OK, I understand why)

**Comment by John-Colvin** [comment]
I could probably delete the `"targetType": "library"` line because it's the default, but it's all going to be redone when we change the doc build system anyway.

**Pull request merged**
